swagger: '2.0'
info:
  title: UID Infrastructure API
  description: rpc server EmptyServer
  contact:
    name: UID Developer Team
    email: dev@uid.com
  version: 1.3.0
consumes:
  - application/json
produces:
  - application/json


paths:
  /rpc/test/GetByID:
    post:
      consumes:
        - application/json
      operationId: test_getByID
      parameters:
        - in: body
          name: ParamList
          required: true
          schema:
            $ref: '#/definitions/testGetByIDParamList'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/rpcspecTestT'

      tags:
        - test
      produces:
        - application/json






definitions:
  rpcspecTestT:
    properties:
      Name:
        type: string
      Age:
        type: integer
        format: int32

  testGetByIDParamList:
    properties:
      companyId:
        type: string
      id:
        type: string


















