swagger: '2.0'
info:
  title: UID Infrastructure API
  description: rpc server EmptyServer
  contact:
    name: UID Developer Team
    email: dev@uid.com
  version: 1.3.0
consumes:
  - application/json
produces:
  - application/json


paths:
  /rpc/test/GetByID:
    post:
      consumes:
        - application/json
      operationId: test_getByID
      parameters:
        - in: body
          name: ParamList
          required: true
          schema:
            $ref: '#/definitions/testGetByIDParamList'
      responses:
        '200':
          description: success
          schema:
            type: object
            x-marshal: true

      tags:
        - test
      produces:
        - application/json


  /rpc/test/GetByIDs:
    post:
      consumes:
        - application/json
      operationId: test_getByIDs
      parameters:
        - in: body
          name: ParamList
          required: true
          schema:
            $ref: '#/definitions/testGetByIDsParamList'
      responses:
        '200':
          description: success

      tags:
        - test
      produces:
        - application/json






definitions:
  testGetByIDParamList:
    properties:
      companyId:
        type: string
      id:
        type: string

  testGetByIDsParamList:
    properties:
      companyId:
        type: string
      id:
        type: string


















