swagger: '2.0'
info:
  title: Json Rpc Infrastructure API
  description: rpc server EmptyServer
  contact:
    name: 
    email: 
  version: 1.3.0
consumes:
  - application/json
produces:
  - application/json


paths:
  /jsonrpc/test/GetByID:
    post:
      consumes:
        - application/json
      operationId: test_getByID
      description: func (t TestT) String() string { panic(&#34;implement me&#34;) } get data by id,  write some  ok
      parameters:
        - in: body
          name: ParamList
          required: true
          schema:
            $ref: '#/definitions/testGetByIDParamList'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/rpc_spec.TestT'

      tags:
        - test
      produces:
        - application/json


  /jsonrpc/test/GetByIDs:
    post:
      consumes:
        - application/json
      operationId: test_getByIDs
      parameters:
        - in: body
          name: ParamList
          required: true
          schema:
            $ref: '#/definitions/testGetByIDsParamList'
      responses:
        '200':
          description: success

      tags:
        - test
      produces:
        - application/json






definitions:
  rpc_spec.TestT.ST:
    properties:
      Inner:
        type: string

  rpc_spec.TestT:
    properties:
      name:
        type: string
      age:
        type: integer
        format: int32
      value:
        type: object
        additionalProperties:
          type: object
      array_val:
        type: array
        items:
          type: integer
          format: int32
      time:
        type: string
        format: date-time
      st:
        $ref: '#/definitions/rpc_spec.TestT.ST'
      A:
        type: integer
        format: int32
      B:
        type: integer
        format: int32
      T:
        type: string
      T3:
        type: string

  testGetByIDParamList:
    properties:
      companyId:
        type: string
        x-nullable: true
      id:
        type: string
        x-nullable: true

  testGetByIDsParamList:
    properties:
      companyId:
        type: string
      id:
        type: string


















