// Code generated by go-bindata. (@generated) DO NOT EDIT.

// Package templates generated by go-bindata.// sources:
// spec/definition.tmpl
// spec/path.tmpl
// spec/spec.tmpl
package templates

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

// Name return file name
func (fi bindataFileInfo) Name() string {
	return fi.name
}

// Size return file size
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}

// Mode return file mode
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}

// ModTime return file modify time
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}

// IsDir return file whether a directory
func (fi bindataFileInfo) IsDir() bool {
	return fi.mode&os.ModeDir != 0
}

// Sys return file is sys mode
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _specDefinitionTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\x93\x41\x6f\xa3\x30\x10\x85\xef\xfc\x8a\x11\xbb\x52\x4e\x90\x3b\xd7\x5d\xad\x36\x07\x2a\xd4\xb4\xe7\x68\x02\x8f\xd4\x95\x6d\x5c\x63\xda\x44\x88\xff\x5e\x01\x69\x42\x42\x42\x52\x95\x0b\x96\x67\xe6\x9b\x79\xa3\xe7\xba\x0e\x28\x43\x2e\x34\xc8\xef\xfe\xc2\x89\x42\xaf\x72\x01\x99\xad\xdc\xce\xc0\xa7\xa0\x69\x3c\xea\xbe\x36\x59\xe4\x14\x2e\xca\xc4\x0a\x25\x9c\x78\x07\x1d\x82\x6d\x38\x4c\x2c\x72\xb1\x5d\x1a\x4e\xd1\x34\x6d\x79\xd4\xde\x2e\x3f\x78\xb3\x81\x7d\xda\x19\x9c\xb0\x20\x4b\xec\x81\x8f\xc8\x61\xa1\xd3\x49\xe0\x6f\x8b\x3c\xa2\xd9\xaf\xf9\x71\xd2\x72\x7e\xce\x9f\x5d\x6e\x10\xb3\xb9\x3d\x6b\xb1\x7e\x45\xea\xae\x26\x71\x96\x75\x4d\x59\x26\xb6\x30\xb0\x4e\xa0\x8c\x86\xed\x74\x76\x61\x57\x31\x9b\x93\xc6\x01\x39\x28\x23\xd9\x5d\x5f\x79\xb8\x70\x50\x4b\x83\xf4\x6c\xf9\x5f\x7a\xf0\x46\x43\xd1\xe4\xb3\xb5\xbc\xf3\x27\xf4\x09\x07\x75\x98\xf5\xc7\x63\xe8\x8c\x46\x42\xff\x73\xf9\xaf\xb0\x8a\xdd\xd4\x9a\xf3\x2e\xa3\x33\x45\x9f\x7c\xce\x1d\x61\x93\x42\x68\x07\x3b\x05\xdd\x06\xba\x92\x92\xd7\x12\x11\x39\x5b\xe1\x06\xf1\x4f\x55\xba\x42\xc5\x6c\xcb\x17\x96\xd3\x5c\xd5\x27\x7d\x03\xfb\xac\xef\x02\x57\x7a\x1a\x3d\xd8\xb2\xe7\x79\x75\x3d\x7e\xa2\x7e\x1b\x1b\xbc\x83\xa8\xab\xb1\xac\x37\xa0\xf0\xef\xf1\xbe\x9f\xa3\xae\x29\x8c\x8b\x0c\xf2\x81\x15\x9a\xa6\x37\x82\xb9\x68\xe2\x1e\x41\xe1\xd1\xe2\x03\xa9\xe1\xb0\xfe\x7e\x1f\x8d\xfd\xd3\x69\xdc\x1f\x06\xa7\xc9\xef\x33\x00\x00\xff\xff\x0f\x09\x66\xa2\xac\x04\x00\x00")

func specDefinitionTmplBytes() ([]byte, error) {
	return bindataRead(
		_specDefinitionTmpl,
		"spec/definition.tmpl",
	)
}

func specDefinitionTmpl() (*asset, error) {
	bytes, err := specDefinitionTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "spec/definition.tmpl", size: 1196, mode: os.FileMode(436), modTime: time.Unix(1611590165, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _specPathTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xa4\x54\xcd\x8e\xda\x30\x10\xbe\xf3\x14\x16\xad\xc4\x09\x58\xf5\x98\x07\xa8\x8a\x54\xaa\x08\x7a\x5f\x0d\xf6\x17\xf0\x2a\xfe\xd9\xb1\xb3\x5d\x14\xe5\xdd\x2b\x9b\xa5\x4d\x96\xd0\x54\x5a\x2e\x24\x93\xc9\x37\xf3\xfd\x38\x6d\xbb\x14\x0a\x95\xb6\x10\x73\x4f\xf1\xf4\xc8\x08\x4d\x1d\x1f\xe3\xd9\x63\x2e\x96\x5d\x37\x13\x7f\x7e\xa9\x57\x57\x62\xb5\x09\x25\x6b\xa3\xa3\x7e\x81\x18\x34\xa4\x96\x55\xc9\xa8\xf4\xeb\xde\x93\x44\xd7\x25\x98\x22\x55\xf7\xbf\xe8\x78\x04\xff\x3c\x7b\xdc\x60\xa2\x0e\x78\x03\xde\xa1\x02\xc3\xca\x49\xe0\xcf\x8c\xaa\x10\x8b\x4f\xeb\xbc\xbc\x8e\xda\xd9\xb0\x7e\x3f\x67\x71\x7f\xd0\x96\xfc\xff\xed\xee\x0e\x4f\x90\xf1\x9f\x8d\xa4\x54\x5e\x80\xea\x92\x9d\x07\x47\x8d\x50\xbc\x1f\x6d\xd5\x1d\x2d\xb7\xe4\x6f\x16\x59\x8a\x08\xe3\x6b\x8a\xa3\xae\xac\x36\x11\x66\xef\x21\x47\xfc\xb9\x52\xc4\xb3\xe8\x6b\x21\xe6\xc4\x4c\xe7\xf9\x04\x65\x1d\x61\x06\xab\x7f\x74\x1b\xab\xc4\x28\xed\x6f\x14\xbe\x3a\x36\x14\xa7\x4c\xa8\x72\x57\x8e\xd0\xe5\x85\xb1\x19\xa3\x23\x4a\xa7\x6d\x04\x4f\x0d\x78\x5d\xda\xa6\xae\xe9\x50\xa3\x10\x91\x1b\x8c\xa2\xf7\xb8\xcc\xda\x76\x70\x60\xe6\xa9\x98\x2e\x42\x91\xdb\x98\xec\x11\x62\x55\xa6\x4a\x1e\xbd\x66\x2f\x53\x32\x77\x5e\xa6\x62\xd7\x5d\xf4\xf5\x2e\xc4\xab\xd2\xd2\xd9\xd0\x98\x7e\x68\x96\x82\xbc\xaf\xb5\xa4\x94\xab\xf5\x53\x70\xf6\xed\x51\xca\x57\x2e\x6e\x54\x16\x65\xe7\xe5\x1e\xfc\xa2\x25\xb6\x88\x27\xf7\x57\x0a\x4f\x4c\x06\x11\x3c\x40\xd5\xb6\x10\x07\xa7\xce\x3d\x96\x96\x0c\x0a\x51\xa6\xf6\xef\x3a\xf4\x93\xce\x78\x6e\x34\x43\xdd\x08\x13\xe4\x09\x86\x86\x39\xb9\x77\x20\x33\x70\x8a\xc7\x6a\xeb\x14\xea\x1f\x64\x7a\x07\x93\x11\xbc\xb3\xa1\xcf\x7c\xf1\xe5\xe1\x61\xd1\x87\x56\x08\x92\xb5\x4f\x80\x85\x08\x8d\x94\x08\x61\x3c\x51\x3b\x84\xa1\xdb\x63\x7b\x4e\xc6\x79\x97\xef\x92\x14\xb7\xd1\xbd\x66\xe0\x52\x89\x74\x1c\x88\x9b\x3e\x3f\x17\x2f\x2e\x2c\xaf\x4e\xb0\x53\x8d\x9c\x70\x77\xd6\xb6\xd7\xa8\xe5\xff\xdf\x01\x00\x00\xff\xff\x54\xda\x77\x62\x98\x05\x00\x00")

func specPathTmplBytes() ([]byte, error) {
	return bindataRead(
		_specPathTmpl,
		"spec/path.tmpl",
	)
}

func specPathTmpl() (*asset, error) {
	bytes, err := specPathTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "spec/path.tmpl", size: 1432, mode: os.FileMode(436), modTime: time.Unix(1611589980, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _specSpecTmpl = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x74\x8e\x3d\x4a\x04\x41\x10\x85\xf3\x3e\xc5\x63\x93\x8d\x6c\x57\xcd\x26\x52\xd8\x64\x12\x11\xd4\x03\x14\x3d\x35\x6b\x4b\xff\x51\x5d\x3d\x06\xc3\xdc\x5d\x7a\x10\x41\x61\x2b\x2a\xea\xa3\xbe\xf7\xea\x17\x5d\x2e\x2c\x03\x8e\xf7\xf6\x74\x34\x3e\xcd\x79\x30\x80\x7a\x0d\x3c\xe0\x7d\x3c\x63\x4c\xb3\x50\x55\x69\x4e\x9b\x30\x9e\x5e\x46\x03\x4c\x5c\x9d\xf8\xa2\x3e\xa7\x01\x52\x1c\x2a\xcb\xc2\x82\x75\xb5\xaf\xfb\xf6\x4c\x91\xb7\xcd\x00\x2e\x27\x25\xa7\x5d\x0a\x24\x8a\x3f\xd6\x33\x2f\x1c\x72\x61\xc1\x1b\x53\xdc\x21\x47\xf2\x61\xc0\xc4\xcb\x63\xf3\x93\x75\xb9\x9f\x17\x96\xba\x87\xdc\xd9\x07\x7b\x32\x2e\xa7\xda\x22\xd7\xae\xbb\x01\x95\x12\xbc\xa3\xde\xe2\xf6\xb3\xe6\x64\x8a\xe4\xa9\xb9\xab\xd8\xac\x2b\x94\x63\x09\xa4\x8c\x43\x21\xfd\x38\xc0\x62\xdb\xcc\x3f\x32\xf1\xec\x93\xef\x7f\xbf\xfc\xcf\x7c\x07\x00\x00\xff\xff\x17\xbd\xf0\x1b\x35\x01\x00\x00")

func specSpecTmplBytes() ([]byte, error) {
	return bindataRead(
		_specSpecTmpl,
		"spec/spec.tmpl",
	)
}

func specSpecTmpl() (*asset, error) {
	bytes, err := specSpecTmplBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "spec/spec.tmpl", size: 309, mode: os.FileMode(436), modTime: time.Unix(1611500399, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"spec/definition.tmpl": specDefinitionTmpl,
	"spec/path.tmpl":       specPathTmpl,
	"spec/spec.tmpl":       specSpecTmpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("nonexistent") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"spec": &bintree{nil, map[string]*bintree{
		"definition.tmpl": &bintree{specDefinitionTmpl, map[string]*bintree{}},
		"path.tmpl":       &bintree{specPathTmpl, map[string]*bintree{}},
		"spec.tmpl":       &bintree{specSpecTmpl, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
